# 配置用户信息 SecurityProperties.java
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: root2019!
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Hikari 连接池配置
    hikari:
      # 连接池名称
      pool-name: HikariCP
      # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 10
      # 一空闲连接最大存户时间（毫秒），超时则被释放（retired），缺省:10分钟
      idleTimeout: 600000
      # 链接超时（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connectionTimeout: 30000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，
      # 参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maxLifetime: 1800000
      connection-test-query: select 1
  # redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password: 123456
    # 连接超时时间（毫秒）
    timeout: 3000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000ms
        # 连接池中的最大空闲连接（负数没有限制）
        max-idle: 2
        # 连接池中的最小空闲连接
        min-idle: 0

mybatis:
  # 配置实体映射类所在包名
  type-aliases-package: org.ylc.note.security.entity
  # 配置mapper xml文件所在路径，这里是一个数组
  # classpath 只会到你的class路径中查找找文件;
  # classpath* 不仅包含class路径，还包括jar文件中(class路径)进行查找
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    # 开启驼峰类型的命名规则
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
